In [2]:
import numpy as np
array1=np.array([1,2,3])
print(type(array1))

array2=np.array([[1,2,3],
                [2,3,4]])
print(array2.shape)


<class 'numpy.ndarray'>
(2, 3)


In [4]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2,array2.dtype)


['1' '2' 'test'] <U11


In [5]:
list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype)

[1. 2. 3.] float64


In [7]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [8]:
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)


[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [9]:
one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [11]:
array1=np.arange(10)
print('array1:\n', array1)

array2=array1.reshape(2,5)
print('array2:\n',array2)

array3=array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [15]:
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2 shape:',array2.shape)
array3=array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)
